// fontconvert.c — TTF -> Adafruit/Arduino_GFX GFXfont header.
//
// Same output format as Adafruit's fontconvert, but sized in PIXELS rather
// than points-at-141dpi, which is what you actually want when laying out a
// fixed 222x480 panel.
//
//   cc fontconvert.c -o fontconvert $(pkg-config --cflags --libs freetype2)
//   ./fontconvert <font.ttf> <pixel-height> <symbol_name> > out.h
//
// Packing rules that MUST hold or drawChar walks off into noise:
//   * 1 bit per pixel, MSB first, rows concatenated with no per-row padding
//   * each GLYPH padded out to a byte boundary, because drawChar indexes the
//     bitmap array by byte at glyph->bitmapOffset

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <ft2build.h>
#include FT_FREETYPE_H

#define FIRST 0x20
#define LAST  0x7E
#define NGLYPH (LAST - FIRST + 1)

static int     bitCount = 0;
static uint8_t bitAccum = 0;
static int     nBytes   = 0;

static void enbit(int value) {
  if (value) bitAccum |= (0x80 >> bitCount);
  if (++bitCount >= 8) {
    printf("0x%02X,", bitAccum);
    if ((++nBytes & 0x0F) == 0) printf("\n  "); else printf(" ");
    bitCount = 0;
    bitAccum = 0;
  }
}

int main(int argc, char *argv[]) {
  if (argc != 4) {
    fprintf(stderr, "usage: %s <font.ttf> <pixel-height> <symbol>\n", argv[0]);
    return 1;
  }
  const char *path = argv[1];
  int         px   = atoi(argv[2]);
  const char *sym  = argv[3];

  FT_Library lib;
  FT_Face    face;
  if (FT_Init_FreeType(&lib))           { fprintf(stderr, "FT init failed\n");        return 1; }
  if (FT_New_Face(lib, path, 0, &face)) { fprintf(stderr, "open %s failed\n", path);  return 1; }
  if (FT_Set_Pixel_Sizes(face, 0, px))  { fprintf(stderr, "set pixel size failed\n"); return 1; }

  struct { int off, w, h, xa, xo, yo; } g[NGLYPH];
  int bitmapOffset = 0;

  printf("// Generated by fontconvert.c from %s at %d px. DO NOT EDIT BY HAND.\n", path, px);
  printf("// Noto Sans is licensed under the SIL Open Font License 1.1.\n");
  printf("#pragma once\n#include <gfxfont.h>\n\n");
  printf("const uint8_t %sBitmaps[] PROGMEM = {\n  ", sym);

  for (int i = 0; i < NGLYPH; i++) {
    int c = FIRST + i;
    if (FT_Load_Char(face, c, FT_LOAD_TARGET_MONO | FT_LOAD_RENDER)) {
      fprintf(stderr, "load char 0x%02X failed\n", c);
      return 1;
    }
    FT_Bitmap *bm = &face->glyph->bitmap;

    g[i].off = bitmapOffset;
    g[i].w   = bm->width;
    g[i].h   = bm->rows;
    g[i].xa  = face->glyph->advance.x >> 6;
    g[i].xo  = face->glyph->bitmap_left;
    g[i].yo  = -face->glyph->bitmap_top;

    for (int y = 0; y < (int)bm->rows; y++)
      for (int x = 0; x < (int)bm->width; x++)
        enbit(bm->buffer[y * bm->pitch + (x / 8)] & (0x80 >> (x & 7)));

    int rem = (bm->width * bm->rows) & 7;      // pad this glyph to a byte
    if (rem) { for (rem = 8 - rem; rem--; ) enbit(0); }
    bitmapOffset += (bm->width * bm->rows + 7) / 8;
  }
  while (bitCount) enbit(0);
  printf("};\n\n");

  printf("const GFXglyph %sGlyphs[] PROGMEM = {\n", sym);
  for (int i = 0; i < NGLYPH; i++) {
    int c = FIRST + i;
    printf("  { %5d, %3d, %3d, %3d, %4d, %4d }%s // 0x%02X '%c'\n",
           g[i].off, g[i].w, g[i].h, g[i].xa, g[i].xo, g[i].yo,
           (i < NGLYPH - 1) ? "," : " ", c, c);
  }
  printf("};\n\n");

  int yAdvance = face->size->metrics.height >> 6;
  printf("const GFXfont %s PROGMEM = {\n"
         "  (uint8_t  *)%sBitmaps,\n"
         "  (GFXglyph *)%sGlyphs,\n"
         "  0x%02X, 0x%02X, %d };\n",
         sym, sym, sym, FIRST, LAST, yAdvance);

  fprintf(stderr, "%-16s %2d px  %d glyphs  %d bitmap bytes  yAdvance %d\n",
          sym, px, NGLYPH, bitmapOffset, yAdvance);
  return 0;
}
